name: stroop_game
description: "A brain training Stroop Game - test your color perception!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Database
  hive_flutter: ^1.1.0

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  # Settings (dark mode toggle, etc.)
  shared_preferences: ^2.3.3

  # Typography
  google_fonts: ^6.2.1

  # Permissions (Android 13+ notifications)
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/image/app_icon.png
    - assets/image/coin.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default:21
